### PR TITLE
Add slots, add ability to use it with custom input components

### PR DESCRIPTION
**Pull request by EgorFront**
I think this way might be more "Headless"

It let to use 3rd party inputs, or custom components.|

Wait for feedback :)

### CODE REVIEW

**Comment by EgorFront** [comment]
I found porblem with types [Here](https://github.com/LoLFactor/vue3-2fa-code-input/pull/1/files#diff-d63e7bf5aa04a2dd2b4e86329f4bf12e8bd3abb3af56d1e5e22a61027e378194R41) and [here](https://github.com/LoLFactor/vue3-2fa-code-input/pull/1/files). I'll check this later, or maybe u can help me

Idk why type of `:ref` doesnt accept the function, and throw an error

**Comment by LoLFactor** [comment]
Hello!

Thank you for the PR. I have reviewed it as best as I can on a Friday evening, but I'm afraid I'm not going to merge it. The reason is, it does not address a fundamental drawback with using slots for this particular use-case.

I get what you tried to do here, I do. Initially I considered this design as well, but I then realized that using slots would mean any any events for the inner inputs would have to be processed in the end-user component (since slotted components are not children of the component containing the slots, but the children of the components **using** the component containing the slots; complete word-salad, I know, but can't find a better way to express this more clearly). I would have no control over the events emitted by the inner inputs, the end-user would.

This means that outside of using whatever I provided as standard in those slots, 2 possibilities existed for the end-user to maintain all the features provided by default:

1. Provide their own inputs, but those inputs would have to respect the specification of whatever I decided should be contained in those slots
2. If their custom inputs did not respect said specification, they have to reimplement most of the logic I wrote for my input inside their own components to support the behaviors I provide by default

What you did with this PR is case 1, but, unfortunately, neither of these is acceptable to me. I went with another variant, which is make the input batteries-included (as far as I could get it to do everything it should as a 2FA input) with the drawback of not directly controlling the styling inside. To compensate, I added styling possibilities (which I documented) and called it a day.

That might not have been the best choice for everyone, but I thought it best, since my best approach to modularity required the end-user to still make efforts for compatibility that rivaled reimplementing the whole thing from scratch. By comparison, if you just want to style it differently, just provide some classes. If you want it to function **fundamentally** differently that how I did it, you might as well just write it from scratch, or fork and adapt it.

The only reason I even made and published this package is because [the most popular alternative before I published this one](https://github.com/bachdgvn/vue-otp-input) was Vue 2 only, and event that one uses the same approach as I have, and for similar reasons, I'd wager.

So, for these reasons, I'm going to have to close this PR without merging it. It's a good effort and I do thank you for your interest. It does address a drawback, but does so while creating others, and I don't think that's a proper solution and it's not in-line with what I think this package should be, which is a quick and simple solution to having a 2FA code input up-and-running fast in your app (the whole reason I made it for myself initially).

If you still think having slots is an important requirement, publish your fork as an alternative package. The more choices, the better, I reckon. 😊

**Comment by LoLFactor** [comment]
Seems you decided to close it yourself before I was done writing. All's well that ends well, I guess.

**Comment by EgorFront** [comment]
Thanks for feedback!

Yes, i decided that i did it wrong way after couple hours of coding xD

**Comment by LoLFactor** [comment]
It wasn't wrong. I haven't actually tested, but it looked like it would work.

It just didn't solve all the issues involved with assuring compatibility with custom inner inputs. And that's not because of anything you did, it's just the way slots work.

Good effort, though.

**Pull request closed without merging**
